name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
 

  web-deploy: # Add this new job
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: 129.151.237.69
          remote-user: opc
          private-ssh-key: ${{ secrets.SSH_KEY }}
          destination-path: /www/wwwroot/gaming
