name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  web-deploy: # Add this new job
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: 129.151.237.69:22
          remote-user: opc
          private-ssh-key: ${{ secrets.SSH_KEY }}
          destination-path: /www/wwwroot/gaming
